### ISSUE TITLE
Undefined variable: lown

### ISSUE THREAD

**Issue by shinokada** [gitllermopalafox/Laravel-OWM#3]
I get Undefined variable: lown. 

Do you have any ideas how to fix it?

In app.php, I have this;

`        Gmopx\LaravelOWM\LaravelOWMServiceProvider::class,
`

In my controller

```
use Gmopx\LaravelOWM\LaravelOWM;

class DashboardController extends Controller
{
    public function index()
    {
        $lowm = new LaravelOWM();
        $current_weather = $lown->getCurrentWeather('london');

        dd($current_weather->temperature);
    }
}
```

Laravel Framework 5.4.23 running on php 7.1.0.

**Comment by jmaurer1994** [comment]
There's a typo on the line:
`$current_weather = $lown->getCurrentWeather('london');`

You have `$lown` instead of `$lowm`

**Comment by shinokada** [comment]
Aha, thanks.
Then can you change your readme file as well. I just copied it from there.

**Comment by gitllermopalafox** [comment]
Thanks @shinokada  and @jmaurer1994 

Typo fixed.
