### ISSUE TITLE
The below code is not working at laraval 5.4.

### ISSUE THREAD

**Issue by armancse100** [gitllermopalafox/Laravel-OWM#5]
public function bar()
{
    $lowm = new LaravelOWM();

    // Get yesterday's date
    $date = new \DateTime();
    $date->add(\DateInterval::createFromDateString('yesterday'));

    $history = $lowm->getWeatherHistory('london', $date);

    dd($history);
}

![untitled](https://user-images.githubusercontent.com/29127685/27033232-0a85606c-4f3e-11e7-806e-034b0758b929.png)

**Comment by jmaurer1994** [comment]
I think it might be because you're passing the DateTime object to $lowm->getWeatherHistory() instead of a value
