### ISSUE TITLE
Is this repo still maintained ? 

### ISSUE THREAD

**Issue by redbonzai** [gitllermopalafox/Laravel-OWM#7]
Hello, 

This package looks interesting and I was wondering if it was still maintained.  I would be happy to contribute to it if it is.  

Thank you, 

Christian Dominguez.

**Comment by redbonzai** [comment]
Perdón ... quise preguntar si este paquete esta todavía mantenida.  Quisiera usarla y contribuir si es asi.  gracias.

**Comment by gitllermopalafox** [comment]
Hi @redbonzai sorry for the late response. Yes, it's still maintained, but I haven't enough time to update it in a continued way.

It'd be great if you can contribute!

I'd very appreciate that.

--------------------------

Una disculpa por tan tardía respuesta, pero sí, aún lo mantengo, aún que no tengo suficiente tiempo para actualizarlo como quisiera.

Sería genial y lo agradecería mucho que pudieras contribuir.

**Comment by redbonzai** [comment]
What things are you needing help with ?  
What are some things that need to be updated, or some features that you want to see on your package ?  
I'll go ahead and fork it.  Glad to help where I can. 
Christian

**Comment by me10071990** [comment]
Hi Gitllermopalafox,

Thank you very much for that you have updated the concept of check the current weather report. As I am doing the same in laravel, However, It's so many challanges from this, Can you explain where I have to put up and how to do in laravel. please help with step so I can learn and do in better way.
