### ISSUE TITLE
Trying to create current weather report as you posted but not get succeed

### ISSUE THREAD

**Issue by me10071990** [gitllermopalafox/Laravel-OWM#8]
Hi,

Thank you for your post, I am following the same and trying implement the same **current weather report** as you posted but not get succeed, please help

**Comment by gitllermopalafox** [comment]
Hi, sorry for the late response.

Please help me answering the following questions...

* What are you trying to do exactly?

* What error(s) are you getting?

* What Laravel version are you using?
